Postillon Newsticker
henrythasler/legendary-dashboard pull request #22
Opened 2020-07-05 08:28 UTC by wdrx

Postillon Newsticker

2020-07-05 10:41 UTC, henrythasler requested changes
Man müsste WISDOM_NUMBER_OF_TEXTS noch aktualisieren, oder generell auf `std::vector` umstellen.

2020-07-06 19:08 UTC, florianeberl commented
> Man müsste WISDOM_NUMBER_OF_TEXTS noch aktualisieren, oder generell auf `std::vector` umstellen.

Done. Ich habe auch die Merge Konflikte mit dem Master behoben.

2020-07-06 19:20 UTC, henrythasler commented
Sollten wir die Änderungsfrequenz auf 5min reduzieren, da wir ja jetzt so viele texte haben?

2020-07-06 19:29 UTC, henrythasler commented
Irgendwie hat es die CI überfordert. Ich lege den mal neu an...

2020-07-06 19:29 UTC, closed without merging