using std::vector instead of a regular array (Attention: couldn't be tested)
henrythasler/legendary-dashboard pull request #23
Opened 2020-07-05 19:31 UTC by florianeberl

Nutzung von std::vector. Allerdings mangels Remote Entwicklung ungetestet...

2020-07-05 21:01 UTC, henrythasler commented
Ich hab dich mal zum Projekt eingeladen. Mach bitte nen Branch auf und bau dort deine Änderungen rein. Dann läuft auch die CI wenn du nen PR stellt. Keine Ahnung warum das bei externe PRs so nicht geht...

2020-07-05 21:05 UTC, henrythasler commented
Der Code an sich müsste eigentlich so laufen.

2020-07-05 21:27 UTC, henrythasler requested changes
=> branch hier im Repo

2020-07-06 18:56 UTC, florianeberl commented
in feature/wisdom integriert

2020-07-06 18:56 UTC, closed without merging